apiVersion: v1
kind: Service   # (1)
metadata:
  name: chess-svc
  labels:
    app: chess
spec:
  type: NodePort   # (2)
  ports:
  - port: 80   # (3)
    targetPort: 80
  selector:
    app: chess   # (4)